spring:
  application:
    name: poker-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/poker_db
    username: chenbotang
    password: 
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

logging:
  level:
    com.poker: DEBUG
    org.springframework.web: DEBUG
